inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\ARI.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\ARI.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\ATL.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\ATL.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\BAL.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\BAL.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\BUF.png -w 1024 -h 1024 ..\prog\datpoolfootball\nfldata\logos\BUF.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\CAR.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\CAR.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\CHI.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\CHI.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\CIN.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\CIN.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\CLE.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\CLE.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\DAL.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\DAL.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\DEN.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\DEN.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\DET.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\DET.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\GB.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\GB.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\HOU.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\HOU.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\IND.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\IND.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\JAX.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\JAX.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\KC.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\KC.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\LA.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\LA.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\LAC.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\LAC.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\MIA.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\MIA.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\MIN.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\MIN.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\NE.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\NE.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\NO.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\NO.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\NYG.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\NYG.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\NYJ.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\NYJ.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\OAK.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\OAK.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\PHI.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\PHI.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\PIT.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\PIT.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\SEA.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\SEA.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\SF.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\SF.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\TB.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\TB.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\TEN.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\TEN.svg
inkscape -z -e ..\prog\DatPoolFootball\NFLData\logos\WAS.png -w 1024 -h 1024 ..\prog\DatPoolFootball\NFLData\logos\WAS.svg
