inkscape -z --export-type=png --export-filename=pngs\ARI.png -w 256 -h 256 svgs\ARI.svg
inkscape -z --export-type=png --export-filename=pngs\ATL.png -w 256 -h 256 svgs\ATL.svg
inkscape -z --export-type=png --export-filename=pngs\BAL.png -w 256 -h 256 svgs\BAL.svg
inkscape -z --export-type=png --export-filename=pngs\BUF.png -w 256 -h 256 svgs\BUF.svg
inkscape -z --export-type=png --export-filename=pngs\CAR.png -w 256 -h 256 svgs\CAR.svg
inkscape -z --export-type=png --export-filename=pngs\CHI.png -w 256 -h 256 svgs\CHI.svg
inkscape -z --export-type=png --export-filename=pngs\CIN.png -w 256 -h 256 svgs\CIN.svg
inkscape -z --export-type=png --export-filename=pngs\CLE.png -w 256 -h 256 svgs\CLE.svg
inkscape -z --export-type=png --export-filename=pngs\DAL.png -w 256 -h 256 svgs\DAL.svg
inkscape -z --export-type=png --export-filename=pngs\DEN.png -w 256 -h 256 svgs\DEN.svg
inkscape -z --export-type=png --export-filename=pngs\DET.png -w 256 -h 256 svgs\DET.svg
inkscape -z --export-type=png --export-filename=pngs\GB.png -w 256 -h 256 svgs\GB.svg
inkscape -z --export-type=png --export-filename=pngs\HOU.png -w 256 -h 256 svgs\HOU.svg
inkscape -z --export-type=png --export-filename=pngs\IND.png -w 256 -h 256 svgs\IND.svg
inkscape -z --export-type=png --export-filename=pngs\JAX.png -w 256 -h 256 svgs\JAX.svg
inkscape -z --export-type=png --export-filename=pngs\KC.png -w 256 -h 256 svgs\KC.svg
inkscape -z --export-type=png --export-filename=pngs\LA.png -w 256 -h 256 svgs\LA.svg
inkscape -z --export-type=png --export-filename=pngs\LAC.png -w 256 -h 256 svgs\LAC.svg
inkscape -z --export-type=png --export-filename=pngs\MIA.png -w 256 -h 256 svgs\MIA.svg
inkscape -z --export-type=png --export-filename=pngs\MIN.png -w 256 -h 256 svgs\MIN.svg
inkscape -z --export-type=png --export-filename=pngs\NE.png -w 256 -h 256 svgs\NE.svg
inkscape -z --export-type=png --export-filename=pngs\NO.png -w 256 -h 256 svgs\NO.svg
inkscape -z --export-type=png --export-filename=pngs\NYG.png -w 256 -h 256 svgs\NYG.svg
inkscape -z --export-type=png --export-filename=pngs\NYJ.png -w 256 -h 256 svgs\NYJ.svg
inkscape -z --export-type=png --export-filename=pngs\OAK.png -w 256 -h 256 svgs\OAK.svg
inkscape -z --export-type=png --export-filename=pngs\PHI.png -w 256 -h 256 svgs\PHI.svg
inkscape -z --export-type=png --export-filename=pngs\PIT.png -w 256 -h 256 svgs\PIT.svg
inkscape -z --export-type=png --export-filename=pngs\SEA.png -w 256 -h 256 svgs\SEA.svg
inkscape -z --export-type=png --export-filename=pngs\SF.png -w 256 -h 256 svgs\SF.svg
inkscape -z --export-type=png --export-filename=pngs\TB.png -w 256 -h 256 svgs\TB.svg
inkscape -z --export-type=png --export-filename=pngs\TEN.png -w 256 -h 256 svgs\TEN.svg
inkscape -z --export-type=png --export-filename=pngs\WAS.png -w 256 -h 256 svgs\WAS.svg
